---
title: "Schedule"
tbl-colwidths: [10, 90]
---

|`Lecture`| `Topic` |
|:---------:|:------------------------------------------------------------------------------|
| 1 | Introduction.  Basics of Probability (sample space, events, sigma-algebra of measurable sets, measurable space, measure, probability measure, non-measurable sets) |
| 2 | Random variables (discrete and continuous), indicators, distribution, expectation, absolute convergence, mean, variance, covariance, conditional probability, independence, law of total probability |
| 3 | Bernoulli process, binomial, geometric, negative binomial, convex functions, strict convexity, Jensen's inequality, entropy, cross-entropy, KL divergence |
| 4 | KL divergence (continued), hypergeometric distribution, exchangeability, tail sum formula |
| 5 | More on exchangeability and hypegeometric distribution, Boole's inequality (union bound), Cauchy-Schwarz inequality, Markov's inequality, Chebyshev's inequality, weak LLN |
| 6 | Convergence of Random Variables (almost sure convergence, convergence in probability, convergence in r-mean, convergence in distribution), strong LLN, CLT, equal in distribution vs equal in probability, examples of convergence |
| 7 | Convergence of Random Variables (continued), relations between different convergence concepts, moment generating function, applications to show convergence in distribution  (from Geometric to Exponential distribution; from Negative Binomial to Gamma distribution) |
| 8 | Sums of random variables, convolution, empirical cumulative distribution function, Glivenko-Cantelli Theorem, Chernoff Inequalities, bounded random variables, Hoeffding's inequality |
| 9 | Proof of Hoeffding's inequality, sub-Gaussian random variables, Hoeffding's lemma, entropy approximation of Binomial, normal approximation of Binomial, Proof of CLT for sums of Bernoulli random variables |
| 10 | A sum of independent normal RVs, application of the CLT, proof of the CLT, Berry-Eseen Theorem, Extensions of CLT |
| 11 | Characteristic function, Levy's continuity theorem, from binomial to Poisson, multinomial distribution, Poissonization of the multinomial, probability generating function (PGF), compounding |
| 12 | Transformation of a single RV, invertible vs. non-invertible transformations, one-to-one differentiable transformations, many-to-one transformations, Cauchy distribution, log-normal distribution, chi-square/gamma distribution, chi distribution, quantile transform, quantile function | 
| 13 | Bivariate jointly continuous random variables, bivariate normal, marginal densities, polar coordinates, linear transformations, invertible linear transformations, rotations, orthogonal transformations | 
 