name: Initialize gh-pages branch on repo creation

on:
  workflow_dispatch:
  create:

jobs:
  setup-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Create empty gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initialising gh-pages branch"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages

